/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.failragequit.game.start;

import com.failragequit.game.play.Choice1;
import com.failragequit.game.play.Choice2;
import com.failragequit.game.play.choice2doors.Door1;
import com.failragequit.game.play.choice2doors.Door2;
import com.failragequit.game.play.choice2doors.Door3;
import java.io.*;
import java.net.*;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Trevor
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Start = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        FindLevel = new javax.swing.JButton();
        LevelIDInput = new javax.swing.JTextField();
        MenuBar = new javax.swing.JMenuBar();
        FileMenu = new javax.swing.JMenu();
        Help = new javax.swing.JMenuItem();
        About = new javax.swing.JMenuItem();
        Documetation = new javax.swing.JMenuItem();
        Separator = new javax.swing.JPopupMenu.Separator();
        Exit = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Game Launcher");

        Start.setText("Start Game");
        Start.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StartActionPerformed(evt);
            }
        });

        jLabel1.setText("Or Enter Level ID to Continue A Previous Game:");

        FindLevel.setText("Find Level");
        FindLevel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FindLevelActionPerformed(evt);
            }
        });
        FindLevel.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                FindLevelKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                FindLevelKeyTyped(evt);
            }
        });

        LevelIDInput.setColumns(3);

        MenuBar.setToolTipText("");

        FileMenu.setText("File");

        Help.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F1, 0));
        Help.setText("Help");
        Help.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HelpActionPerformed(evt);
            }
        });
        FileMenu.add(Help);

        About.setText("About");
        About.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AboutActionPerformed(evt);
            }
        });
        FileMenu.add(About);

        Documetation.setText("Documentation");
        Documetation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DocumetationActionPerformed(evt);
            }
        });
        FileMenu.add(Documetation);
        FileMenu.add(Separator);

        Exit.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, java.awt.event.InputEvent.ALT_MASK));
        Exit.setText("Exit");
        Exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitActionPerformed(evt);
            }
        });
        FileMenu.add(Exit);

        MenuBar.add(FileMenu);

        setJMenuBar(MenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Start)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LevelIDInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(FindLevel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Start)
                    .addComponent(jLabel1)
                    .addComponent(FindLevel)
                    .addComponent(LevelIDInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public static boolean exists() {
        try {
            // Create a URL for the desired page
            URL url = new URL("http://failragequit.com/activate/game.txt");
            BufferedReader in = new BufferedReader(new InputStreamReader(url.openStream()));
            String str;
            while ((str = in.readLine()) != null) {
                System.out.println(str);
                if (str == "") {
                    System.out.println("t" + str + "t");
                    return true;

                }

            }
            in.close();
        } catch (MalformedURLException e) {
            return true;
        } catch (IOException e) {
            return true;
        }

        return true;
    }

    @SuppressWarnings("StringEquality")
    private void FindLevelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FindLevelActionPerformed
        // TODO add your handling code here:
       /* try {
         Thread.sleep(1000);
         } catch(InterruptedException ex) {
         Thread.currentThread().interrupt();
         }*/
        if (exists()) {
            String LevelID = LevelIDInput.getText();

            int ID = Integer.parseInt(LevelID);

            switch (LevelID) {
                case "1":
                    Choice1 choice1 = new Choice1();
                    choice1.setVisible(true);
                    dispose();
                    break;

                case "2":
                    Choice2 choice2 = new Choice2();
                    choice2.setVisible(true);
                    dispose();
                    break;
                case "31":
                    Door1 door1 = new Door1();
                    door1.setVisible(true);
                    dispose();
                    break;
                case "32":
                    Door2 door2 = new Door2();
                    door2.setVisible(true);
                    dispose();
                    break;
                case "33":
                    Door3 door3 = new Door3();
                    door3.setVisible(true);
                    dispose();
                    break;
                default:
                    LevelIDInput.setText(null);
                    JOptionPane.showMessageDialog(null, "Please Enter Valid Level ID", LevelID, JOptionPane.ERROR_MESSAGE);
                    break;
            }
        } else {
            Deactivate deactivate = new Deactivate();
            deactivate.setVisible(true);
            dispose();
        }

    }//GEN-LAST:event_FindLevelActionPerformed

    private void HelpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HelpActionPerformed
        // TODO add your handling code here:
        Help help = new Help();
        help.setVisible(true);

    }//GEN-LAST:event_HelpActionPerformed

    private void AboutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AboutActionPerformed
        // TODO add your handling code here:
        About about = new About();
        about.setVisible(true);
    }//GEN-LAST:event_AboutActionPerformed

    private void StartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StartActionPerformed
        // TODO add your handling code here:
        Choice1 choice1 = new Choice1();
        choice1.setVisible(true);
        dispose();
    }//GEN-LAST:event_StartActionPerformed

    private void ExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_ExitActionPerformed

    private void FindLevelKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_FindLevelKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_FindLevelKeyPressed

    private void FindLevelKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_FindLevelKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_FindLevelKeyTyped

    private void DocumetationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DocumetationActionPerformed
        // TODO add your handling code here:
        Docs docs = new Docs();
        docs.setVisible(true);
    }//GEN-LAST:event_DocumetationActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                if (exists() == true) {
                    new Main().setVisible(true);
                } else {
                    Deactivate deactivate = new Deactivate();
                    deactivate.setVisible(true);
                }

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem About;
    private javax.swing.JMenuItem Documetation;
    private javax.swing.JMenuItem Exit;
    private javax.swing.JMenu FileMenu;
    private javax.swing.JButton FindLevel;
    private javax.swing.JMenuItem Help;
    private javax.swing.JTextField LevelIDInput;
    private javax.swing.JMenuBar MenuBar;
    private javax.swing.JPopupMenu.Separator Separator;
    private javax.swing.JButton Start;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
