/*
 * Copyright Trevor Eady 2014
 * ================================================
 * ====================LICENCE:====================
 * ================================================
 */
package com.failragequit.game.play;

/**
 *
 * @author Trevor Eady
 */
public class Safe extends javax.swing.JFrame {

    /**
     * Creates new form Safe
     */
    public Safe() {
        initComponents();
    }
    //Declare all of thevariables enterd on the form and store them here
    boolean tbool1 = true;
    boolean tbool2 = true;
    boolean tbool3 = true;
    boolean tbool4 = true;
    boolean tbool5 = true;
    boolean tbool6 = true;
    boolean tbool7 = true;
    boolean tbool8 = true;
    //Declare all of the answer variables
    boolean tabool1 = true;
    boolean tabool2 = true;
    boolean tabool3 = true;
    boolean tabool4 = true;
    boolean tabool5 = true;
    boolean tabool6 = true;
    boolean tabool7 = true;
    boolean tabool8 = true;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        bi1 = new javax.swing.JPanel();
        toggle1 = new javax.swing.JLabel();
        tButtonon1 = new javax.swing.JButton();
        tButtonoff1 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        bi2 = new javax.swing.JPanel();
        toggle2 = new javax.swing.JLabel();
        tButtonon2 = new javax.swing.JButton();
        tButtonoff2 = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        bi3 = new javax.swing.JPanel();
        toggle3 = new javax.swing.JLabel();
        tButtonon3 = new javax.swing.JButton();
        tButtonoff3 = new javax.swing.JButton();
        jLabel19 = new javax.swing.JLabel();
        bi4 = new javax.swing.JPanel();
        toggle4 = new javax.swing.JLabel();
        tButtonon4 = new javax.swing.JButton();
        tButtonoff4 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        bi5 = new javax.swing.JPanel();
        toggle5 = new javax.swing.JLabel();
        tButtonon5 = new javax.swing.JButton();
        tButtonoff5 = new javax.swing.JButton();
        jLabel27 = new javax.swing.JLabel();
        bi6 = new javax.swing.JPanel();
        toggle6 = new javax.swing.JLabel();
        tButtonon6 = new javax.swing.JButton();
        tButtonoff6 = new javax.swing.JButton();
        jLabel25 = new javax.swing.JLabel();
        bi7 = new javax.swing.JPanel();
        toggle7 = new javax.swing.JLabel();
        tButtonon7 = new javax.swing.JButton();
        tButtonoff7 = new javax.swing.JButton();
        jLabel21 = new javax.swing.JLabel();
        bi8 = new javax.swing.JPanel();
        toggle8 = new javax.swing.JLabel();
        tButtonon8 = new javax.swing.JButton();
        tButtonoff8 = new javax.swing.JButton();
        jLabel23 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("you try and open the safe but its locked");

        jLabel2.setText("jLabel2");

        toggle1.setText("ON");

        tButtonon1.setText("ON");
        tButtonon1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tButtonon1ActionPerformed(evt);
            }
        });

        tButtonoff1.setText("OFF");
        tButtonoff1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tButtonoff1ActionPerformed(evt);
            }
        });

        jLabel7.setText("Switch 1");

        javax.swing.GroupLayout bi1Layout = new javax.swing.GroupLayout(bi1);
        bi1.setLayout(bi1Layout);
        bi1Layout.setHorizontalGroup(
            bi1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bi1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(tButtonon1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tButtonoff1))
            .addGroup(bi1Layout.createSequentialGroup()
                .addGroup(bi1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(bi1Layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(toggle1))
                    .addGroup(bi1Layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(jLabel7)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        bi1Layout.setVerticalGroup(
            bi1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bi1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(toggle1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(bi1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tButtonon1)
                    .addComponent(tButtonoff1)))
        );

        toggle2.setText("ON");

        tButtonon2.setText("ON");
        tButtonon2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tButtonon2ActionPerformed(evt);
            }
        });

        tButtonoff2.setText("OFF");
        tButtonoff2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tButtonoff2ActionPerformed(evt);
            }
        });

        jLabel13.setText("Switch 2");

        javax.swing.GroupLayout bi2Layout = new javax.swing.GroupLayout(bi2);
        bi2.setLayout(bi2Layout);
        bi2Layout.setHorizontalGroup(
            bi2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bi2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(tButtonon2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tButtonoff2))
            .addGroup(bi2Layout.createSequentialGroup()
                .addGroup(bi2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(bi2Layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(toggle2))
                    .addGroup(bi2Layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(jLabel13)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        bi2Layout.setVerticalGroup(
            bi2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bi2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(toggle2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(bi2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tButtonon2)
                    .addComponent(tButtonoff2)))
        );

        toggle3.setText("ON");

        tButtonon3.setText("ON");
        tButtonon3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tButtonon3ActionPerformed(evt);
            }
        });

        tButtonoff3.setText("OFF");
        tButtonoff3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tButtonoff3ActionPerformed(evt);
            }
        });

        jLabel19.setText("Switch 3");

        javax.swing.GroupLayout bi3Layout = new javax.swing.GroupLayout(bi3);
        bi3.setLayout(bi3Layout);
        bi3Layout.setHorizontalGroup(
            bi3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bi3Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(tButtonon3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tButtonoff3))
            .addGroup(bi3Layout.createSequentialGroup()
                .addGroup(bi3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(bi3Layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(toggle3))
                    .addGroup(bi3Layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(jLabel19)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        bi3Layout.setVerticalGroup(
            bi3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bi3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel19)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(toggle3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(bi3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tButtonon3)
                    .addComponent(tButtonoff3)))
        );

        toggle4.setText("ON");

        tButtonon4.setText("ON");
        tButtonon4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tButtonon4ActionPerformed(evt);
            }
        });

        tButtonoff4.setText("OFF");
        tButtonoff4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tButtonoff4ActionPerformed(evt);
            }
        });

        jLabel11.setText("Switch 4");

        javax.swing.GroupLayout bi4Layout = new javax.swing.GroupLayout(bi4);
        bi4.setLayout(bi4Layout);
        bi4Layout.setHorizontalGroup(
            bi4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bi4Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(tButtonon4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tButtonoff4))
            .addGroup(bi4Layout.createSequentialGroup()
                .addGroup(bi4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(bi4Layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(toggle4))
                    .addGroup(bi4Layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(jLabel11)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        bi4Layout.setVerticalGroup(
            bi4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bi4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(toggle4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(bi4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tButtonon4)
                    .addComponent(tButtonoff4)))
        );

        toggle5.setText("ON");

        tButtonon5.setText("ON");
        tButtonon5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tButtonon5ActionPerformed(evt);
            }
        });

        tButtonoff5.setText("OFF");
        tButtonoff5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tButtonoff5ActionPerformed(evt);
            }
        });

        jLabel27.setText("Switch 5");

        javax.swing.GroupLayout bi5Layout = new javax.swing.GroupLayout(bi5);
        bi5.setLayout(bi5Layout);
        bi5Layout.setHorizontalGroup(
            bi5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bi5Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(tButtonon5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tButtonoff5))
            .addGroup(bi5Layout.createSequentialGroup()
                .addGroup(bi5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(bi5Layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(toggle5))
                    .addGroup(bi5Layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(jLabel27)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        bi5Layout.setVerticalGroup(
            bi5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bi5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel27)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(toggle5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(bi5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tButtonon5)
                    .addComponent(tButtonoff5)))
        );

        toggle6.setText("ON");

        tButtonon6.setText("ON");
        tButtonon6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tButtonon6ActionPerformed(evt);
            }
        });

        tButtonoff6.setText("OFF");
        tButtonoff6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tButtonoff6ActionPerformed(evt);
            }
        });

        jLabel25.setText("Switch 6");

        javax.swing.GroupLayout bi6Layout = new javax.swing.GroupLayout(bi6);
        bi6.setLayout(bi6Layout);
        bi6Layout.setHorizontalGroup(
            bi6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bi6Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(tButtonon6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tButtonoff6))
            .addGroup(bi6Layout.createSequentialGroup()
                .addGroup(bi6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(bi6Layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(toggle6))
                    .addGroup(bi6Layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(jLabel25)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        bi6Layout.setVerticalGroup(
            bi6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bi6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel25)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(toggle6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(bi6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tButtonon6)
                    .addComponent(tButtonoff6)))
        );

        toggle7.setText("ON");

        tButtonon7.setText("ON");
        tButtonon7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tButtonon7ActionPerformed(evt);
            }
        });

        tButtonoff7.setText("OFF");
        tButtonoff7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tButtonoff7ActionPerformed(evt);
            }
        });

        jLabel21.setText("Switch 7");

        javax.swing.GroupLayout bi7Layout = new javax.swing.GroupLayout(bi7);
        bi7.setLayout(bi7Layout);
        bi7Layout.setHorizontalGroup(
            bi7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bi7Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(tButtonon7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tButtonoff7))
            .addGroup(bi7Layout.createSequentialGroup()
                .addGroup(bi7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(bi7Layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(toggle7))
                    .addGroup(bi7Layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(jLabel21)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        bi7Layout.setVerticalGroup(
            bi7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bi7Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel21)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(toggle7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(bi7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tButtonon7)
                    .addComponent(tButtonoff7)))
        );

        toggle8.setText("ON");

        tButtonon8.setText("ON");
        tButtonon8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tButtonon8ActionPerformed(evt);
            }
        });

        tButtonoff8.setText("OFF");
        tButtonoff8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tButtonoff8ActionPerformed(evt);
            }
        });

        jLabel23.setText("Switch 8");

        javax.swing.GroupLayout bi8Layout = new javax.swing.GroupLayout(bi8);
        bi8.setLayout(bi8Layout);
        bi8Layout.setHorizontalGroup(
            bi8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bi8Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(tButtonon8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tButtonoff8))
            .addGroup(bi8Layout.createSequentialGroup()
                .addGroup(bi8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(bi8Layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(toggle8))
                    .addGroup(bi8Layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(jLabel23)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        bi8Layout.setVerticalGroup(
            bi8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bi8Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel23)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(toggle8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(bi8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tButtonon8)
                    .addComponent(tButtonoff8)))
        );

        jButton3.setText("Ok");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2)
            .addComponent(jLabel1)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bi1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bi5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(118, 118, 118)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(bi2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bi6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(bi3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bi4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(bi7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bi8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton3)
                .addGap(208, 208, 208))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(bi1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bi2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bi3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bi4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(bi5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bi6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bi7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bi8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addComponent(jButton3)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
//the below statements handle the inputs
    private void tButtonon1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tButtonon1ActionPerformed
        // TODO add your handling code here:
        toggle1.setText("ON");
        tbool1 = true;
    }//GEN-LAST:event_tButtonon1ActionPerformed

    private void tButtonon4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tButtonon4ActionPerformed
        toggle4.setText("ON");
        tbool4 = true;
    }//GEN-LAST:event_tButtonon4ActionPerformed

    private void tButtonon2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tButtonon2ActionPerformed
        toggle2.setText("ON");
        tbool2 = true;
    }//GEN-LAST:event_tButtonon2ActionPerformed

    private void tButtonon3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tButtonon3ActionPerformed
        toggle3.setText("ON");
        tbool3 = true;
    }//GEN-LAST:event_tButtonon3ActionPerformed

    private void tButtonon7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tButtonon7ActionPerformed
        toggle7.setText("ON");
        tbool7 = true;
    }//GEN-LAST:event_tButtonon7ActionPerformed

    private void tButtonon8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tButtonon8ActionPerformed
        toggle8.setText("ON");
        tbool8 = true;
    }//GEN-LAST:event_tButtonon8ActionPerformed

    private void tButtonon6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tButtonon6ActionPerformed
        toggle6.setText("ON");
        tbool6 = true;
    }//GEN-LAST:event_tButtonon6ActionPerformed

    private void tButtonon5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tButtonon5ActionPerformed
        toggle5.setText("ON");
        tbool5 = true;
    }//GEN-LAST:event_tButtonon5ActionPerformed

    private void tButtonoff1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tButtonoff1ActionPerformed
        toggle1.setText("OFF");
        tbool1 = false;
    }//GEN-LAST:event_tButtonoff1ActionPerformed

    private void tButtonoff2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tButtonoff2ActionPerformed
        toggle2.setText("OFF");
        tbool2 = false;
    }//GEN-LAST:event_tButtonoff2ActionPerformed

    private void tButtonoff3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tButtonoff3ActionPerformed
        toggle3.setText("OFF");
        tbool3 = false;
    }//GEN-LAST:event_tButtonoff3ActionPerformed

    private void tButtonoff4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tButtonoff4ActionPerformed
        toggle4.setText("OFF");
        tbool4 = false;
    }//GEN-LAST:event_tButtonoff4ActionPerformed

    private void tButtonoff5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tButtonoff5ActionPerformed
        toggle5.setText("OFF");
        tbool5 = false;
    }//GEN-LAST:event_tButtonoff5ActionPerformed

    private void tButtonoff6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tButtonoff6ActionPerformed
        toggle6.setText("OFF");
        tbool6 = false;
    }//GEN-LAST:event_tButtonoff6ActionPerformed

    private void tButtonoff7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tButtonoff7ActionPerformed
        toggle7.setText("OFF");
        tbool7 = false;
    }//GEN-LAST:event_tButtonoff7ActionPerformed

    private void tButtonoff8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tButtonoff8ActionPerformed
        toggle8.setText("OFF");
        tbool8 = false;
    }//GEN-LAST:event_tButtonoff8ActionPerformed
        //Handels the input from the ok buttton
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        //Checks all the variables if they equal the answer variables 
        if (tbool1 == tabool1 && tbool2 == tabool2 && tbool3 == tabool3 && tbool4 == tabool4 && tbool5 == tabool5 && tbool6 == tabool6 && tbool7 == tabool7 && tbool8 == tabool8) {
            //opens a new window and closes this one
            Win win = new Win();
            win.setVisible(true);
            dispose();
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Safe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Safe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Safe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Safe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Safe().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bi1;
    private javax.swing.JPanel bi2;
    private javax.swing.JPanel bi3;
    private javax.swing.JPanel bi4;
    private javax.swing.JPanel bi5;
    private javax.swing.JPanel bi6;
    private javax.swing.JPanel bi7;
    private javax.swing.JPanel bi8;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JButton tButtonoff1;
    private javax.swing.JButton tButtonoff2;
    private javax.swing.JButton tButtonoff3;
    private javax.swing.JButton tButtonoff4;
    private javax.swing.JButton tButtonoff5;
    private javax.swing.JButton tButtonoff6;
    private javax.swing.JButton tButtonoff7;
    private javax.swing.JButton tButtonoff8;
    private javax.swing.JButton tButtonon1;
    private javax.swing.JButton tButtonon2;
    private javax.swing.JButton tButtonon3;
    private javax.swing.JButton tButtonon4;
    private javax.swing.JButton tButtonon5;
    private javax.swing.JButton tButtonon6;
    private javax.swing.JButton tButtonon7;
    private javax.swing.JButton tButtonon8;
    private javax.swing.JLabel toggle1;
    private javax.swing.JLabel toggle2;
    private javax.swing.JLabel toggle3;
    private javax.swing.JLabel toggle4;
    private javax.swing.JLabel toggle5;
    private javax.swing.JLabel toggle6;
    private javax.swing.JLabel toggle7;
    private javax.swing.JLabel toggle8;
    // End of variables declaration//GEN-END:variables
}
